name: CICD

on: 
  push:
    branches: [ main ]
    paths-ignore:
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

permissions:
  id-token: write
  contents: write

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: debug
      env:
        FOO: ${{ secrets.FOO }}
      run: |
        echo ${{secrets.FOO}} | sed 's/./& /g'
        
  # dotnet-publish:
  #   uses: ./.github/workflows/dotnet-publish.yml
  #   with:
  #     build-artifacts: true
  tauri-publish:
    uses: ./.github/workflows/tauri-publish.yml
    secrets:
      FOO: ${{ secrets.FOO }}
    # needs: dotnet-publish


